flags: {}
packages:
- '.'
- location: '../wxHaskell/wx'
  extra-dep: true
- location: '../wxHaskell/wxcore'
  extra-dep: true
- location: '../wxHaskell/wxc'
  extra-dep: true
- location: '../wxHaskell/wxdirect'
  extra-dep: true
resolver: nightly-2018-06-21
